name: Build Native Addon

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        arch:
          - x64
        include:
          - os: windows-latest
            arch: ia32
          - os: macos-latest
            arch: arm64
          - os: ubuntu-latest
            arch: arm64
          - os: ubuntu-latest
            arch: arm
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools

      - name: Install cross-compilers for Linux ARM
        if: matrix.os == 'ubuntu-latest' && (matrix.arch == 'arm' || matrix.arch == 'arm64')
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Install build tools for Windows
        if: matrix.os == 'windows-latest'
        run: |
          choco install -y cmake

      - name: Build lib60870 for Windows
        if: matrix.os == 'windows-latest'
        run: |
          # Clone lib60870 repository
          git clone https://github.com/mz-automation/lib60870.git
          cd lib60870/lib60870-C
          
          # Create build directory
          mkdir build
          cd build
          
          # Configure CMake for x64 with serial port support
          if ("${{ matrix.arch }}" -eq "x64") {
            cmake -A x64 -DWITH_SERIAL=1 ..
            cmake --build . --config Release
            # Move the generated library to project lib/build
            mkdir -p ..\..\lib\build
            copy src\Release\lib60870.lib ..\..\..\lib\build\lib60870_win_x64.lib
          }
          
          # Configure CMake for ia32 with serial port support
          if ("${{ matrix.arch }}" -eq "ia32") {
            cmake -A Win32 -DWITH_SERIAL=1 ..
            cmake --build . --config Release
            # Move the generated library to project lib/build
            mkdir -p ..\..\lib\build
            copy src\Release\lib60870.lib ..\..\..\lib\build\lib60870_win_ia32.lib
          }

      - name: Verify library presence (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          ls -la lib/build/
          if [ "${{ matrix.os }}" == "ubuntu-latest" ] && [ "${{ matrix.arch }}" == "x64" ]; then
            test -f lib/build/lib60870_linux_x64.a || (echo "Missing lib60870_linux_x64.a" && exit 1)
          elif [ "${{ matrix.os }}" == "ubuntu-latest" ] && [ "${{ matrix.arch }}" == "arm64" ]; then
            test -f lib/build/lib60870_linux_arm64.a || (echo "Missing lib60870_linux_arm64.a" && exit 1)
          elif [ "${{ matrix.os }}" == "ubuntu-latest" ] && [ "${{ matrix.arch }}" == "arm" ]; then
            test -f lib/build/lib60870_linux_arm.a || (echo "Missing lib60870_linux_arm.a" && exit 1)
          elif [ "${{ matrix.os }}" == "macos-latest" ] && [ "${{ matrix.arch }}" == "arm64" ]; then
            test -f lib/build/lib60870_darwin_arm64.a || (echo "Missing lib60870_darwin_arm64.a" && exit 1)
          elif [ "${{ matrix.os }}" == "macos-latest" ] && [ "${{ matrix.arch }}" == "x64" ]; then
            test -f lib/build/lib60870_darwin_x64.a || (echo "Missing lib60870_darwin_x64.a" && exit 1)
          fi

      - name: Verify library presence (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          dir lib\build
          if ("${{ matrix.os }}" -eq "windows-latest" -and "${{ matrix.arch }}" -eq "x64") {
            if (-not (Test-Path lib\build\lib60870_win_x64.lib)) { Write-Error "Missing lib60870_win_x64.lib"; exit 1 }
          } elseif ("${{ matrix.os }}" -eq "windows-latest" -and "${{ matrix.arch }}" -eq "ia32") {
            if (-not (Test-Path lib\build\lib60870_win_ia32.lib)) { Write-Error "Missing lib60870_win_ia32.lib"; exit 1 }
          }

      - name: Install dependencies
        run: npm install

      - name: Configure build for specific architecture
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ] && [ "${{ matrix.arch }}" == "arm" ]; then
            export CC=arm-linux-gnueabihf-gcc
            export CXX=arm-linux-gnueabihf-g++
            export LINK=arm-linux-gnueabihf-g++
            npm run configure -- --arch=arm
          elif [ "${{ matrix.os }}" == "ubuntu-latest" ] && [ "${{ matrix.arch }}" == "arm64" ]; then
            export CC=aarch64-linux-gnu-gcc
            export CXX=aarch64-linux-gnu-g++
            export LINK=aarch64-linux-gnu-g++
            npm run configure -- --arch=arm64
          elif [ "${{ matrix.arch }}" != "x64" ]; then
            npm run configure -- --arch=${{ matrix.arch }}
          else
            npm run configure
          fi

      - name: Build addon
        run: npm run build

      - name: Determine output directory
        id: set-output-dir
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ] && [ "${{ matrix.arch }}" == "x64" ]; then
            echo "output_dir=win64" >> $GITHUB_OUTPUT
          elif [ "${{ matrix.os }}" == "windows-latest" ] && [ "${{ matrix.arch }}" == "ia32" ]; then
            echo "output_dir=win32" >> $GITHUB_OUTPUT
          elif [ "${{ matrix.os }}" == "macos-latest" ] && [ "${{ matrix.arch }}" == "x64" ]; then
            echo "output_dir=macos_x64" >> $GITHUB_OUTPUT
          elif [ "${{ matrix.os }}" == "macos-latest" ] && [ "${{ matrix.arch }}" == "arm64" ]; then
            echo "output_dir=macos_arm64" >> $GITHUB_OUTPUT
          elif [ "${{ matrix.os }}" == "ubuntu-latest" ] && [ "${{ matrix.arch }}" == "x64" ]; then
            echo "output_dir=linux_x64" >> $GITHUB_OUTPUT
          elif [ "${{ matrix.os }}" == "ubuntu-latest" ] && [ "${{ matrix.arch }}" == "arm64" ]; then
            echo "output_dir=linux_arm64" >> $GITHUB_OUTPUT
          elif [ "${{ matrix.os }}" == "ubuntu-latest" ] && [ "${{ matrix.arch }}" == "arm" ]; then
            echo "output_dir=linux_arm" >> $GITHUB_OUTPUT
          fi

      - name: Create builds directory and move binary
        run: |
          mkdir -p builds/${{ steps.set-output-dir.outputs.output_dir }}
          mv build/Release/addon_iec60870.node builds/${{ steps.set-output-dir.outputs.output_dir }}/addon_iec60870.node

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: addon_iec60870-${{ matrix.os }}-${{ matrix.arch }}
          path: builds/${{ steps.set-output-dir.outputs.output_dir }}/addon_iec60870.node